trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  Location: "canadacentral"
  ServiceConnectionName: "spBicep"
  RunNumber: $(Build.BuildNumber)

jobs:
- job:
  steps:
  - task: AzureCLI@2
    displayName: Az CLI Deploy Management Groups
    name: create_mgs
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment tenant create \
        --template-file infra-as-code/bicep/modules/managementGroups/managementGroups.bicep \
        --parameters parTopLevelManagementGroupPrefix="$(MGMT_PREFIX)" parTopLevelManagementGroupDisplayName="$(MGMT_GROUP_NAME)" \
        --location $(Location) \
        --name create_mgs-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Custom Policy Definitions
    name: create_policy_defs
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep  \
        --parameters parTargetManagementGroupId="$(MGMT_PREFIX)" \
        --location $(Location) \
        --management-group-id $(MGMT_PREFIX) \
        --name create_policy_defs-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Custom Role Definitions
    name: create_rbac_roles
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/modules/customRoleDefinitions/customRoleDefinitions.bicep \
        --parameters parAssignableScopeManagementGroupId="$(MGMT_PREFIX)" \
        --location $(Location) \
        --management-group-id $(MGMT_PREFIX) \
        --name create_rbac_roles-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Logging Resource Group
    name: create_logging_rg
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(LOGGING_SUB_ID)
        az deployment sub create \
        --template-file infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep \
        --parameters parResourceGroupName=$(LOGGING_RG) parLocation=$(Location) \
        --location $(Location) \
        --name create_logging_rg-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Logging
    name: create_logging
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $emv:loggingSubId
        az deployment group create \
        --resource-group $(LOGGING_RG) \
        --template-file infra-as-code/bicep/modules/logging/logging.bicep \
        --parameters parLogAnalyticsWorkspaceName="$(MGMT_PREFIX)-log-analytics" \
        --name create_logging-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Hub Network Resource Group
    name: create_hub_network_rg
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(HUB_NETWORK_SUB_ID)
        az deployment sub create \
        --template-file infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep \
        --parameters parResourceGroupName=$(HUB_NETWORK_RG) parLocation=$(Location) \
        --location $(Location) \
        --name create_hub_network_rg-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Hub Network
    name: create_hub_network
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(HUB_NETWORK_SUB_ID)
        az deployment group create \
        --resource-group $(HUB_NETWORK_RG) \
        --template-file infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep \
        --parameters parCompanyPrefix=$(MGMT_PREFIX) parAzBastionEnabled=$(BASTION_ENABLED) parDdosEnabled=$(DDOS_ENABLED) parAzFirewallEnabled=$(FIREWALL_ENABLED) \
        --name create_hub_network-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Role Assignment
    name: create_role_assignment
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroup.bicep \
        --parameters parRoleDefinitionId="8e3af657-a8ff-443c-a75c-2fe8c4bcb635" parAssigneePrincipalType="Group" parAssigneeObjectId=$(TENANT_ADMIN_OBJECT_ID) \
        --location $(Location) \
        --management-group-id $(MGMT_PREFIX)-platform \
        --name create_role_assignment-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Subscription Placements
    name: create_subscription_placement
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/orchestration/subPlacementAll/subscriptionPlacementAll.bicep \
        --parameters parTopLevelManagementGroupPrefix $(MGMT_PREFIX) parPlatformManagementMgSubs="[$(MGMT_SUB_ID)]" parPlatformConnectivityMgSubs="[$(CONNECTIVITY_SUB_ID)]" parPlatformIdentityMgSubs="[$(IDENTITY_SUB_ID)]" parLandingZonesCorpMgSubs="[$(CORP_SUB_ID)] parLandingZonesOnlineMgSubs=[$(ONLINE_SUB_ID)]" \
        --location $(Location) \
        --management-group-id $(MGMT_PREFIX) \
        --name create_subscription_placement-$(RunNumber)

  - task: AzureCLI@2
    displayName: Deploy Default Policy Assignments
    name: create_policy_assignments
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep \
        --parameters parTopLevelManagementGroupPrefix=$(MGMT_PREFIX) parLogAnalyticsWorkSpaceAndAutomationAccountLocation="canadacentral" parLogAnalyticsWorkspaceResourceId="/subscriptions/$(MGMT_SUB_ID)/resourceGroups/$(MGMT_PREFIX)-logging/providers/Microsoft.OperationalInsights/workspaces/$(MGMT_PREFIX)-log-analytics" parAutomationAccountName="$(MGMT_PREFIX)-automation-account" parMsDefenderForCloudEmailSecurityContact="support@microagemanitoba.com" \
        --location $(Location) \
        --management-group-id $(MGMT_PREFIX) \
        --name create_policy_assignments-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Spoke Network Resource Group
    name: create_spoke_network_rg
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(SPOKE_NETWORK_SUB_ID)
        az deployment sub create \
        --template-file infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep \
        --parameters parResourceGroupName=$(SPOKE_NETWORK_RG) parLocation=$(Location) \
        --location $(Location) \
        --name create_spoke_network_rg-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Spoke Network
    name: create_spoke_network
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(SPOKE_NETWORK_SUB_ID)
        az deployment group create \
        --resource-group $(SPOKE_NETWORK_RG) \
        --template-file infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.bicep \
        --parameters parSpokeNetworkName="$(MGMT_PREFIX)-AVD-VNet" \
        --name create_spoke_network-$(RunNumber)