trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  Location: "canadacentral"
  ServiceConnectionName: "spBicep"
  RunNumber: $(Build.BuildNumber)

jobs:
- job: Deploy Management Groups Policies and Roles
  steps:
  - task: AzureCLI@2
    displayName: Az CLI Deploy Management Groups
    name: create_mgs
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment tenant create \
        --template-file infra-as-code/bicep/modules/managementGroups/managementGroups.bicep \
        --parameters parTopLevelManagementGroupPrefix="$(MGMT_PREFIX)" parTopLevelManagementGroupDisplayName="$(MGMT_GROUP_NAME)" \
        --location $(Location) \
        --name create_mgs-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Custom Policy Definitions
    name: create_policy_defs
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep  \
        --parameters parTargetManagementGroupId="$(MGMT_PREFIX)" \
        --location $(Location) \
        --management-group-id $(MGMT_PREFIX) \
        --name create_policy_defs-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Custom Role Definitions
    name: create_rbac_roles
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/modules/customRoleDefinitions/customRoleDefinitions.bicep \
        --parameters parAssignableScopeManagementGroupId="$(MGMT_PREFIX)" \
        --location $(Location) \
        --management-group-id $(MGMT_PREFIX) \
        --name create_rbac_roles-$(RunNumber)
- job: Deploy Resource Groups
  steps:
  - task: AzureCLI@2
    displayName: Az CLI Deploy Logging Resource Group
    name: create_logging_rg
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(LOGGING_SUB_ID)
        az deployment sub create \
        --template-file infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep \
        --parameters parResourceGroupName=$(LOGGING_RG) parLocation=$(Location) \
        --location $(Location) \
        --name create_logging_rg-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Hub Network Resource Group
    name: create_hub_network_rg
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(CONNECTIVITY_SUB_ID)
        az deployment sub create \
        --template-file infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep \
        --parameters parResourceGroupName="$(MGMT_PREFIX)-Hub-Vnet-RG" parLocation=$(Location) \
        --location $(Location) \
        --name create_hub_network_rg-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Identity Resource Group
    name: create_identity_rg
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(IDENTITY_SUB_ID)
        az deployment sub create \
        --template-file infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep \
        --parameters parResourceGroupName="$(MGMT_PREFIX)-Identity-RG" parLocation=$(Location) \
        --location $(Location) \
        --name create_identity_rg-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Azure Files Resource Group
    name: create_af_rg
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(CORP_SUB_ID)
        az deployment sub create \
        --template-file infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep \
        --parameters parResourceGroupName="$(MGMT_PREFIX)-AF-RG" parLocation=$(Location) \
        --location $(Location) \
        --name create_af_rg-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy AVD Resource Group
    name: create_avd_rg
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(CORP_SUB_ID)
        az deployment sub create \
        --template-file infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep \
        --parameters parResourceGroupName="$(MGMT_PREFIX)-AVD-RG" parLocation=$(Location) \
        --location $(Location) \
        --name create_avd_rg-$(RunNumber)
- job: Deploy Logging
  steps:
  - task: AzureCLI@2
    displayName: Az CLI Deploy Logging
    name: create_logging
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(LOGGING_SUB_ID)
        az deployment group create \
        --resource-group $(LOGGING_RG) \
        --template-file infra-as-code/bicep/modules/logging/logging.bicep \
        --parameters parLogAnalyticsWorkspaceName="$(MGMT_PREFIX)-log-analytics" \
        --name create_logging-$(RunNumber)
- job: Deploy Hub and AVD Spoke
  steps:
  - task: AzureCLI@2
    displayName: Az CLI Deploy Hub Network
    name: create_hub_network
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(CONNECTIVITY_SUB_ID)
        az deployment group create \
        --resource-group "$(MGMT_PREFIX)-Hub-Vnet-RG" \
        --template-file infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep \
        --parameters parCompanyPrefix=$(MGMT_PREFIX) \
        --name create_hub_network-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Hub Network GW
    name: create_hub_network_gw
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(CONNECTIVITY_SUB_ID)
        az deployment group create \
        --resource-group "$(MGMT_PREFIX)-Hub-Vnet-RG" \
        --template-file infra-as-code/bicep/modules/virtualNetworkGateways/deploy.bicep \
        --parameters name="$(MGMT_PREFIX)-GW" location=$(Location) gatewayType="Vpn" vpnGatewayGeneration="Generation1" skuName="Basic" vNetResourceId="/subscriptions/$(CONNECTIVITY_SUB_ID)/resourceGroups/$(MGMT_PREFIX)-Hub-Vnet-RG/providers/Microsoft.Network/virtualNetworks/$(MGMT_PREFIX)-hub-canadacentral" \
        --name create_hub_network_gw-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Spoke Network Peered to Hub
    name: create_spoke_network
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/orchestration/hubPeeredSpoke/hubPeeredSpoke.bicep \
        --parameters parTopLevelManagementGroupPrefix=$(MGMT_PREFIX) parPeeredVnetSubscriptionId=$(CORP_SUB_ID) parResourceGroupNameForSpokeNetworking=$(MGMT_PREFIX)-AVD-Vnet-RG parSpokeNetworkName=$(MGMT_PREFIX)-AVD-Vnet parSpokeToHubRouteTableName="AVD-to-hub" parHubVirtualNetworkId="/subscriptions/$(CONNECTIVITY_SUB_ID)/resourceGroups/$(MGMT_PREFIX)-Hub-Vnet-RG/providers/Microsoft.Network/virtualNetworks/$(MGMT_PREFIX)-hub-canadacentral" \
        --location $(Location) \
        --management-group-id $(MGMT_PREFIX) \
        --name create_spoke_network-$(RunNumber)
- job: Deploy Identity RG
  steps:
  - task: AzureCLI@2
    displayName: Az CLI Deploy Domain Controller
    name: create_dc
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(IDENTITY_SUB_ID)
        az deployment group create \
        --resource-group "$(MGMT_PREFIX)-Identity-RG" \
        --template-file infra-as-code/bicep/modules/active-directory-new-domain/main.bicep \
        --parameters location=$(Location) adminUsername="microage" adminPassword=$(DC_PASSWORD) domainName=$(DOMAIN_NAME) vmSize="Standard_D2as_V5" virtualMachineName=$(MGMT_PREFIX)-DC virtualNetworkName=$(MGMT_PREFIX)-Identity-Vnet virtualNetworkAddressRange="10.5.0.0/16" privateIPAddress="10.5.1.4" subnetName="default" subnetRange="10.5.1.0/24" networkInterfaceName="$(MGMT_PREFIX)-DC-NIC" \
        --name create_dc-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Peer Identity Vnet to Hub
    name: peer_identity_vnet_to_hub
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(IDENTITY_SUB_ID)
        az deployment group create \
        --resource-group "$(MGMT_PREFIX)-Identity-RG" \
        --template-file infra-as-code/bicep/modules/vnetPeering/vnetPeering.bicep \
        --parameters parDestinationVirtualNetworkId="/subscriptions/$(CONNECTIVITY_SUB_ID)/resourceGroups/$(MGMT_PREFIX)-Hub-Vnet-RG/providers/Microsoft.Network/virtualNetworks/$(MGMT_PREFIX)-hub-canadacentral" parSourceVirtualNetworkName="$(MGMT_PREFIX)-Identity-Vnet" parDestinationVirtualNetworkName="$(MGMT_PREFIX)-hub-canadacentral" \
        --name peer_identity_vnet_to_hub-$(RunNumber)

  - task: AzureCLI@2
    displayName: Az CLI Peer Hub Vnet to Identity
    name: peer_hub_vnet_to_identity
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(CONNECTIVITY_SUB_ID)
        az deployment group create \
        --resource-group "$(MGMT_PREFIX)-Hub-Vnet-RG" \
        --template-file infra-as-code/bicep/modules/vnetPeering/vnetPeering.bicep \
        --parameters parDestinationVirtualNetworkId="/subscriptions/$(IDENTITY_SUB_ID)/resourceGroups/$(MGMT_PREFIX)-Identity-RG/providers/Microsoft.Network/virtualNetworks/$(MGMT_PREFIX)-Identity-Vnet" parSourceVirtualNetworkName="$(MGMT_PREFIX)-hub-canadacentral" parDestinationVirtualNetworkName="$(MGMT_PREFIX)-Identity-Vnet" \
        --name peer_hub_vnet_to_identity-$(RunNumber)
- job: Deploy Storage Account
  steps:
  - task: AzureCLI@2
    displayName: Az CLI Create Storage Account
    name: create_sa
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(CORP_SUB_ID)
        az deployment group create \
        --resource-group "$(MGMT_PREFIX)-AF-RG" \
        --template-file infra-as-code/bicep/modules/storageAccounts/deploy.bicep \
        --parameters skuName="Premium_LRS" largeFileSharesState="Enabled" \
        --name create_sa-$(RunNumber)
- job: Deploy role and policy assignments and place subscriptions
  steps:
  - task: AzureCLI@2
    displayName: Az CLI Deploy Role Assignment
    name: create_role_assignment
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroup.bicep \
        --parameters parRoleDefinitionId="8e3af657-a8ff-443c-a75c-2fe8c4bcb635" parAssigneePrincipalType="Group" parAssigneeObjectId=$(TENANT_ADMIN_OBJECT_ID) \
        --location $(Location) \
        --management-group-id $(MGMT_PREFIX)-platform \
        --name create_role_assignment-$(RunNumber)

  - task: DownloadSecureFile@1
    name: subPlacementParams
    displayName: 'Download sub placement paraments'
    inputs:
      secureFile: 'subPlacementAll.parameters.all.json'

  - task: AzureCLI@2
    displayName: Az CLI Deploy Subscription Placements
    name: create_subscription_placement
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/orchestration/subPlacementAll/subPlacementAll.bicep \
        --parameters @$(subPlacementParams.secureFilePath) \
        --location $(Location) \
        --management-group-id $(MGMT_PREFIX) \
        --name create_subscription_placement-$(RunNumber)

  - task: AzureCLI@2
    displayName: Deploy Default Policy Assignments
    name: create_policy_assignments
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep \
        --parameters parTopLevelManagementGroupPrefix=$(MGMT_PREFIX) parLogAnalyticsWorkSpaceAndAutomationAccountLocation="canadacentral" parLogAnalyticsWorkspaceResourceId="/subscriptions/$(MGMT_SUB_ID)/resourceGroups/$(LOGGING_RG)/providers/Microsoft.OperationalInsights/workspaces/$(MGMT_PREFIX)-log-analytics" parAutomationAccountName="$(MGMT_PREFIX)-automation-account" parMsDefenderForCloudEmailSecurityContact="support@microagemanitoba.com" \
        --location $(Location) \
        --management-group-id $(MGMT_PREFIX) \
        --name create_policy_assignments-$(RunNumber)